### ISSUE TITLE
Fix FAQ

### ISSUE THREAD

**Issue by juancwu** [LaurierCS/Website#111]
- [x] Hover Effect: like the event cards
- [ ] Laggy open/close

**Comment by UsamaMo** [comment]
I will try to take care of this

**Comment by juancwu** [comment]
Only the hover effect was completed, the laggy open/close from the faq is still there.

**Comment by UsamaMo** [comment]
Sorry what laggy open/close?

**Comment by juancwu** [comment]
> Sorry what laggy open/close?

When opening an FAQ item, the animation is not smooth. Shown in the video.

[Screencast from 10-06-2023 11:28:10 AM.webm](https://github.com/LaurierCS/Website/assets/46619361/734584cf-d039-4a8f-9808-7939a4c5876b)


Just FYI, this has nothing to do with your updates, it has been a problem since the website was deployed.
