### ISSUE TITLE
[Feature] Update Stats Section Gradient Wave

### ISSUE THREAD

**Issue by juancwu** [LaurierCS/Website#142]
The gradient wave that is prod right now was cooked up in a hurry and its not the best looking one. We need to fix that and make our website look even sexier.

Here is how it should look like (I think as long as we can match the colour and have a decent wave its good, so we don't have to match it 100%):

![image](https://github.com/LaurierCS/Website/assets/46619361/820bfa99-6272-47b3-a5bb-0e6362611227)

**Comment by aidantrabs** [comment]
bonus points if you make it animated
