### ISSUE TITLE
Footer UI Updates

### ISSUE THREAD

**Issue by juancwu** [LaurierCS/Website#82]
- [x] Add ":" to the end of "Here's a token of appreciation from Dug"
- [x] Make back to top arrow colour: "#E7EBF5" and 0.8 opacity
- [ ] Add more x-axis padding to the "congratulations..." text, right now it seems really closed up when it is in mobile view.

**Comment by UsamaMo** [comment]
Will try to do this as well

**Comment by UsamaMo** [comment]
the first two points are done
